### ISSUE TITLE
OSS License?

### ISSUE THREAD

**Issue by benley** [paperg/awsudo#11]
I'm packaging awsudo for inclusion in NixOS, and one of the bits of metadata required is which open-source license the project uses. It appears that there is currently no license or copyright declaration for the code in this repository. Would you consider adding one? Something as simple as dropping a copy of your preferred license's text in a LICENSE file would be sufficient.

**Comment by ktilcu** [comment]
@benley thanks for the request. Let me check with legal and get something in here.

**Comment by benley** [comment]
Thanks!

**Comment by ktilcu** [comment]
@benley I added the MIT license. Thanks for bringing this up to our attention.
