### ISSUE TITLE
How to pass environment variables into a command run by awsudo

### ISSUE THREAD

**Issue by marceloboeira** [paperg/awsudo#14]
When using awsudo I can't run commands that require inline params/env values. e.g.:

 `awsudo -u production ADAPTER=kinesis PORT=5000 ./foo` - it returns as `ADAPTER=kinesis command not found`

**Comment by ktilcu** [comment]
Thanks for opening an issue! You can prepend those declarations to `awsudo` and it will work.  

```shell
ADAPTER=kinesis PORT=5000 awsudo -u production ./foo
```

**Comment by marceloboeira** [comment]
@ktilcu thanks for the tip.

But we still can't set AWS things right?

e.g.: `AWS_REGION=eu-central-1 ADAPTER=kinesis PORT=5000 awsudo -u production ./foo - will clean the region`

based on: https://github.com/makethunder/awsudo/blob/master/awsudo/main.py#L28

**Comment by ktilcu** [comment]
Normally that is set in the config (`~/.aws/config`). What situation are you running into that you want to set that at runtime?

**Comment by marceloboeira** [comment]
@ktilcu I'm gonna try to do that, but maybe we could try to whitelist the AWS things that you want to clean from ENV rather than cleaning all of them.
