### ISSUE TITLE
Support profiles for awsrotate

### ISSUE THREAD

**Issue by perbergland** [paperg/awsudo#4]
It would be super convenient if awsrotate could rotate keys for any profile in the ~/.aws/credentials file, 

```
[default]
aws_access_key_id = XXXX
aws_secret_access_key = YYYY

[rootaccount]
aws_access_key_id = ZZZZZ
aws_secret_access_key = QQQQQ
```

and then run `awsrotate -u rootaccount` to update the ZZZZZ and QQQQQ entries

**Comment by bitglue** [comment]
How's this: #4

**Comment by perbergland** [comment]
Thanks @bitglue - that commit looks perfect but I would need to rebase on source master for me to try it since your fork is 20 commits behind. I'll try to find some time later today.

**Comment by bitglue** [comment]
Sorry, I totally messed that up. I meant to say: #5
