### ISSUE TITLE
How to assume role with specified expired time

### ISSUE THREAD

**Issue by Gujarats** [paperg/awsudo#9]
using `aws sts assume-role` there is an option like `--duration-second` .
How to achieve this using awsudo ?
I was thinking I can set the expired time in the `~/.aws/config` file like : 
```shell
role_arn = arn:aws:iam::YOUR_ROLE
source_profile = YOUR_SOURCE_PROFILE
region = YOUR_REGION
duration =900
```
is this the correct way to do it ? since I can't confirm if this is working.

**Comment by ktilcu** [comment]
@Gujarats Sorry for the super long delay. If you are looking for a way to be able to run multiple commands as a particular user you may be able to do something like `awsudo -u user bash`. That should drop you in a shell that has that users credentials set. Then you run your commands and when finished just logout. Does that help?

**Comment by Gujarats** [comment]
@ktilcu I still don't get it, what I'm looking for in `awsudo` is to asssume the role with specified duration, since now AWS has the ability to extends the session for `assume role`  to 12 hours.

**Comment by ktilcu** [comment]
@Gujarats I don't think `awsudo` does that. I assume the purpose of assuming the role for a specific duration is to run multiple commands as a user knowing that you will no longer have that role assumed in the future. My assumption is likely wrong. Can you tell me more about what you are wanting to use `awsudo` to accomplish?
